name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: mkdir bin && make build
      - name: run
        # run: make sanity_check
        run: make test
      - name: clean
        run: make clean
